services:
  db:
    image: mysql:8
    container_name: myapp-mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: firstlaravelprojectCRUD
    ports:
      - "3306:3306"        
    volumes:
      - dbdata:/var/lib/mysql

  pma:
    image: phpmyadmin:latest
    container_name: myapp-phpmyadmin
    environment:
      PMA_HOST: myapp-mysql   # must match the container_name above
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  dbdata:
